version: '3.8'

services:
  mongo:
      container_name: mongodb
      image: mongo
      env_file:
        - .env
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      restart: always
      ports: 
        - "27017:27017"
      volumes:
        - mongo-volume:/data/db
      networks:
        - mongo_net

  app: 
    container_name: exampleapp
    restart: always
    build: .
    ports:
      - "5000:3000"
    depends_on: 
      - mongo
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:  ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    networks:
      - mongo_net

volumes:
  mongo-volume:  
    name: mongo-volume  

networks:
  mongo_net:
    driver: bridge